package hu.konczdam.forma1.dev.datainit;

import hu.konczdam.forma1.model.Formula1Team;
import hu.konczdam.forma1.repository.Formula1TeamRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.time.Year;

@Component
@RequiredArgsConstructor
@Profile("dev")
public class TestDataLoader implements CommandLineRunner {
    private final Formula1TeamRepository formula1TeamRepository;

    @Override
    public void run(String... args) {
        // Generated by chatgpt
        Formula1Team team1 = new Formula1Team("Scuderia Ferrari", Year.of(1950), 16, true);
        Formula1Team team2 = new Formula1Team("McLaren", Year.of(1966), 12, true);
        Formula1Team team3 = new Formula1Team("Williams", Year.of(1977), 9, true);
        Formula1Team team4 = new Formula1Team("Mercedes", Year.of(1954), 7, true);
        Formula1Team team5 = new Formula1Team("Red Bull", Year.of(2005), 4, true);
        Formula1Team team6 = new Formula1Team("Lotus", Year.of(1958), 7, false);
        Formula1Team team7 = new Formula1Team("Renault", Year.of(1977), 2, true);
        Formula1Team team8 = new Formula1Team("BRM", Year.of(1951), 1, false);
        Formula1Team team9 = new Formula1Team("Cooper", Year.of(1950), 2, false);
        Formula1Team team10 = new Formula1Team("Benetton", Year.of(1986), 2, false);
        Formula1Team team11 = new Formula1Team("Brawn GP", Year.of(2009), 1, false);
        Formula1Team team12 = new Formula1Team("Brabham", Year.of(1962), 2, false);
        Formula1Team team13 = new Formula1Team("Matra", Year.of(1968), 1, false);
        Formula1Team team14 = new Formula1Team("Tyrrell", Year.of(1970), 2, false);
        Formula1Team team15 = new Formula1Team("Aston Martin", Year.of(2021), 0, true);

        formula1TeamRepository.save(team1);
        formula1TeamRepository.save(team2);
        formula1TeamRepository.save(team3);
        formula1TeamRepository.save(team4);
        formula1TeamRepository.save(team5);
        formula1TeamRepository.save(team6);
        formula1TeamRepository.save(team7);
        formula1TeamRepository.save(team8);
        formula1TeamRepository.save(team9);
        formula1TeamRepository.save(team10);
        formula1TeamRepository.save(team11);
        formula1TeamRepository.save(team12);
        formula1TeamRepository.save(team13);
        formula1TeamRepository.save(team14);
        formula1TeamRepository.save(team15);
    }

}
